INVALID_CATEGORY = "invalid_category"
VALID_YEAR = 2020
INVALID_YEAR_LOW = 1900
INVALID_YEAR_HIGH = 2100

BASE_IMPORT_URL = "/import"
IMPORT_VALID_CATEGORY = "vinhos"

BASE_EXPORT_URL = "/export"
EXPORT_VALID_CATEGORY = "espumantes"

BASE_PRODUCTION_URL = "/production"

BASE_PROCESSING_URL = "/processing"
PROCESSING_VALID_CATEGORY = "viniferas"

BASE_COMMERCIALIZATION_URL = "/commercialization"
